In [1]:
import pandas as pd

In [2]:
data = [['rhushi',56,],['akash', 45]]

In [3]:
data

[['rhushi', 56], ['akash', 45]]

In [4]:
pd.DataFrame(data, columns=["name","Marks"])

     name  Marks
0  rhushi     56
1   akash     45

In [7]:
data = {"a":[1, 2, 3, 4], "b":[5, 6, 6, 7]}

In [8]:
data

{'a': [1, 2, 3, 4], 'b': [5, 6, 6, 7]}

In [11]:
df = pd.DataFrame(data)

In [12]:
df

   a  b
0  1  5
1  2  6
2  3  6
3  4  7

In [13]:
import numpy as np

In [20]:
arr = np.array([[1,2],[3,4]])

In [21]:
arr

array([[1, 2],
       [3, 4]])

In [26]:
df = pd.DataFrame(arr, columns=["A", "B"])

In [27]:
df

   A  B
0  1  2
1  3  4

In [30]:
df = pd.read_excel("data_sheet_1.xlsx")

In [31]:
df

        name School  marks
0     rhushi    ERD     97
1  dhanashri    TRF     98
2       yash    FER     86
3     mahesh    HTF     56
4     pranav    ETF     65
5      aryan    DER     56
6      kunal    DTG     54

In [33]:
df = pd.read_csv("data_sheet_1.csv")

In [34]:
df

        name School  marks
0     rhushi    ERD     97
1  dhanashri    TRF     98
2       yash    FER     86
3     mahesh    HTF     56
4     pranav    ETF     65
5      aryan    DER     56
6      kunal    DTG     54

In [39]:
df = pd.read_json("data.json")

In [40]:
df

     name    lang
0  rhushi  python
1    yash    java

In [41]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [42]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [43]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [44]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [47]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [53]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [54]:
df.shape

(244, 7)