In [7]:
import pandas as pd

In [10]:
df = pd.read_csv("data_cleaning_sample.csv")

In [42]:
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [43]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date  Age Group
0  False  False  False   False  False      False      False
1  False   True  False   False  False      False      False
2  False  False  False   False  False      False      False
3  False   True  False   False  False      False      False
4  False  False  False   False  False      False      False
5   True  False  False   False  False       True      False
6  False  False  False   False  False      False      False
7  False  False  False   False  False      False      False
8  False   True  False   False  False      False      False

In [44]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
Age Group    0
dtype: int64

In [45]:
df.dropna()

    Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

In [46]:
df.dropna(axis=1)

          City Gender              Email Age Group
0     New York      F  alice@example.com     Adult
1        Delhi      M    charlie@example     Minor
2  Los Angeles      M    bob@example.com     Adult
3        Delhi      M    charlie@example     Minor
4       Mumbai      M  david@example.com     Adult
5        Delhi      F     eve@domain.com     Adult
6     New York      F  alice@example.com     Adult
7     New York      F  alice@example.com     Adult
8        Delhi      M    charlie@example     Minor

In [47]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
5        0  28.0        Delhi      F     eve@domain.com           0     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021     Minor

In [48]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [49]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [50]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult

In [51]:
(df["City"].str.contains("delhi",case=False))

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [52]:
type(df["City"].str.contains("delhi",case=False))

pandas.core.series.Series

In [53]:
df["Email"].str.split("@")[0:9]

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [54]:
df2 = df.dropna().copy()

In [55]:
df2

    Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

In [56]:
df2.info

<bound method DataFrame.info of     Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult>

In [57]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x >= 18 else "Minor")

In [58]:
df2

    Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult

In [59]:
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [60]:
gender_map = {"M": "Male", "F": "Female"}
df["Gender"] = df["Gender"].map(gender_map)

In [61]:
df

      Name   Age         City  Gender              Email   Join Date Age Group
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     Adult
6    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor

In [62]:
df["City"].replace({"Del": "Delhi", "Mum": "Mumbai"})

0       New York
1          Delhi
2    Los Angeles
3          Delhi
4         Mumbai
5          Delhi
6       New York
7       New York
8          Delhi
Name: City, dtype: object